### ISSUE TITLE
081416_15 start/end times are incorrect?

### ISSUE THREAD

**Issue by kaitlyngaynor** [kaitlyngaynor/hopland-hunting#23]
Cropping 081416_15 track makes it look weird. Here's the timeline of events from the metadata, and here are the tracks. Worth a closer look—do you have the ability to look into this @amcinturff ?

Start: 06:10
Harvest: 06:32
End: 07:50

I think that the start and/or end times may have to be adjusted based on the movement paths.

RAW TRACK:
![Screen Shot 2021-12-14 at 9 36 53 AM](https://user-images.githubusercontent.com/29489999/146050475-02cfa9b6-eb74-464c-a4de-b763ee7056e0.png)

CROPPED TRACK (between 06:10 and 07:50):
![Screen Shot 2021-12-14 at 9 36 45 AM](https://user-images.githubusercontent.com/29489999/146050453-09e2a58a-bf1f-43a5-9f98-4acb77242c13.png)

**Comment by amcinturff** [comment]
I looked at the raw track. It looks like they started moving before
official sunrise (about 5:25), so that explains why some of the path from
HQ to the harvest site is missing. However, they didn't actually end at
7:50, but rather about 8:00am. So, we could either change both boundaries
of the clip (Start: 5:25; End:8:00) to reflect their actual behavior, or we
could keep the start time consistent with other hunters and the law and
just change the end time. My instinct is the first, since I suspect they
were searching for deer before 6:10 even if htey knew they couldn't fire
yet (and if they saw a prize buck I bet they would have shot anyway)

**Comment by kaitlyngaynor** [comment]
Ok sounds good. I changed the start and end time as suggested in the new version of the doc igotu_metadata_times_cleaned_17Dec2021.csv.

FYI the start times _should_ be the time that we handed them the logger, NOT the time of sunrise. Many of them are around 5am. So in this case, I think it was just an error in data recording.
